### ISSUE TITLE
Output not preserved on error

### ISSUE THREAD

**Issue by AJHenry** [cenk1cenk2/listr2#137]
When using the default renderer, and the following options

Renderer options:

```ts
concurrent: false,
rendererOptions: {
    collapse: false,
    showSubtasks: true
}
```

Task options: 

```ts
persistentOutput: true,
exitOnError: true,
bottomBar: Infinity
```

When an error is throw by a task, the output that it previously posted to the bottom bar is cleared, even though output from previous successful tasks are preserved. 

Is there a way to preserve output even if an error is thrown?
If not, perhaps a task option for `preserveOutputOnError` can be added?

**Comment by cenk1cenk2** [comment]
Yes there should be. I think i can obtain that behavior with moving some rendering conditions around. I will have to check and return back to you. Eta will be this weekend possibly.

**Comment by AJHenry** [comment]
Cool, I'll try and take a crack at it tonight and if I can't get it I'll refer it to you

**Comment by AJHenry** [comment]
I was able to fix the issue, however if we change the logic to print out on errors, it will be a breaking change. Did you want to go the path of changing the default behavior of `persistentOutput` to _also_ print when a stage errors?

Or do you want to keep the current behavior and create a new flag like `persistentErrorOutput` to avoid a breaking change?

**Comment by cenk1cenk2** [comment]
I would definetly prefer a renderer flag without a breaking change.

**Comment by cenk1cenk2** [comment]
Closing this issue since it is merged on beta channel for now for the reasons explained [here](https://github.com/cenk1cenk2/listr2/pull/138#issuecomment-673565781).

https://github.com/cenk1cenk2/listr2/tree/beta
