### ISSUE TITLE
Question: Is there a way to modify a task's title after all the subtasks have completed successfully

### ISSUE THREAD

**Issue by Shriram-Balaji** [cenk1cenk2/listr2#141]
I'm currently using Listr2 to run a set of subtasks, and I wanted to know if there's a way to change the title of the parent, on succesful completion. For eg. in the snippet below, I'd like to change `Uploading` to `Uploaded` once all the subtasks are done. 

```js
// `uploadTasks` -> an array of ListrTask objects
new Listr([
 title: "Uploading some docs",
 task: async (_, task) => task.newListr(uploadTasks, listrOptions);
]});
```

I'm not sure if I'm missing something here, but since `task.newListr` returns a `Listr` object, and not a `Promise`, I cannot update the `task.title` from there. Would be great if you could let me know of a way to do this. Thanks!

**Comment by cenk1cenk2** [comment]
Yes, there should be. Since the task is a stateful class, if you convert the `uploadTasks` to a function that returns a an array of ListrTask objects and pass in the task as a variable like `parentTask`, I am sure that you can achieve that with adding a ghost task without a title at the end that manipulates the `parentTask.title`.

**Comment by cenk1cenk2** [comment]
You can access the readme section from: https://github.com/cenk1cenk2/listr2#access-parent-task-from-subtasks

Hope this resolves your question. You can now change the parent task title without any trickery even though rest of the functionality like skipping it is mostly useless.

**Comment by Shriram-Balaji** [comment]
@cenk1cenk2 thanks a lot for adding a built-in way to do this, and addressing this request very quickly! 😄 

Quick question though, I have added a ghost task to modify the parent title in the end, but is this guaranteed to work after the other subtasks have complement when in `concurrent` mode?

**Comment by cenk1cenk2** [comment]
If its running concurrent no. But you can do two sets of subtasks maybe. Hmm so it might not be the perfect solution.

**Comment by cenk1cenk2** [comment]
Idk maybe we can add a callback function to run it after it but it would be the old way of doing things.

**Comment by erykpiast** [comment]
I have a similar use-case I believe and I think a callback wouldn't be so bad. I'd like to run some arbitrary code if the Listr failed (so ex. if any of the tasks failed and I've set `exitOnError` flag to `true`). Basically, I'd like to so something like:

```javascript
new Listr([
 {
    title: 'Foo',
    task: (_, task) => task.newListr([/* many tasks, any may fail */], {
      callback(err) {
        if (err !== null) {
         cleanup();
         task.parent += ` (failed miserably with error ${err.message})`;
       } else {
         task.parent += ' (finished successfully 🎉)';
       }
    })
  },
  {
    title: 'Some other task',
    task: ...
  }
});
```

I tried with promises - `task.newListr(...).run().catch(teardown)`, but UI breaks then :(

**Comment by cenk1cenk2** [comment]
https://github.com/cenk1cenk2/listr2#access-parent-task-from-subtasks

I guess this one should work in your case just add a last task where you set parent.title.

I am on mobile so unfortunetly can not write an example at the moment, but that should work.

If your tasks are async you should wrap them with two sync tasks where first one will hold the async tasks and the second one will change the title.

**Comment by cenk1cenk2** [comment]
If you can not manage it. I will have a look at creating an alternative way to do this this weekend. It seems straightforward enough.

**Comment by erykpiast** [comment]
The part which I'm struggling with is getting a function called after the inner list finished the work (either with or without success). Accessing the parent task isn't the issue at all. I'd really like to avoid repeating my cleanup code in each inner task. I guess I could do it but it'd and get what I want, but it'd be super repetitive.

**Comment by cenk1cenk2** [comment]
@erykpiast is it okay for you to open up a new issue with a reproducable repository. Because i read it couple of times and did not understand what you are trying to achieve exactly, let alone it being achivable at all.

**Comment by erykpiast** [comment]
Yea, that's a great idea. Sorry for the confusion! Here it is: https://github.com/cenk1cenk2/listr2/issues/257
