### ISSUE TITLE
v2.6.0 is missing from https://replicate.npmjs.com/listr2

### ISSUE THREAD

**Issue by Sharrison2** [cenk1cenk2/listr2#154]
The latest version 2.6.0 of listr2 is not being replicated in npm - https://replicate.npmjs.com/listr2.   It shows the latest version as 2.5.1.  I just thought you should know

I have raised this with npm support but so far they all they have said is it can take a few hours to replicate, but this was published 11 days ago and counting

Since I am mirroring npm from replicate.npmjs.com, build processes are failing because other packages are relying on this version.

**Comment by cenk1cenk2** [comment]
Okay i will republish it and hopefully this will be solved.

**Comment by cenk1cenk2** [comment]
I kindly request you to try it again with v2.6.1 since I have failed to do so on mobile and close this issue if resolved.

**Comment by Sharrison2** [comment]
Thanks.  Replicated now has all the versions
