### ISSUE TITLE
Skipping a Task with an active prompt

### ISSUE THREAD

**Issue by AJHenry** [cenk1cenk2/listr2#173]
In one of my use cases, I would like the user to press a key if they want to interrupt the current task, otherwise continue on.

For example, I have an enquirer prompt that is something like the following `Press any key to abort, otherwise continuing in 10 seconds...`

However, when I skip the task while the prompt is active, the task get skipped but the prompt is still active in the background. 

If I try to cancel the prompt, I always get hit with an error so that too exits the pipeline

```ts

    enquirer.on("prompt", async prompt => {
      await delay(10000);
      prompt.cancel();
    });

```

Lastly, if I try to skip the prompt with the built in skip function (which accepts a `Promise<boolean>` type), the prompt disappears into the background but is still active until it gets skipped

```ts
const status = await task.prompt({
    name: "continue",
    type: "input",
    message: `Press any key to abort, continuing in 10 seconds otherwise`,
    skip: async () => {
        await delay(10000);
        return true;
    }
});
```

What would be the appropriate approach for this pattern? I can make a contribution for it as well

**Comment by cenk1cenk2** [comment]
Yeah, there is no handling for that you are right about it. This kind of seems straight forward at first sight.

- So [task.prompt](https://github.com/cenk1cenk2/listr2/blob/fed5da85190c89419fbdcd1d6213b8b6ce113762/src/lib/task-wrapper.ts#L85) is set to true when there is a prompt and I also use it to return any errors from the prompt module. 
- Maybe instead of true, we set it to the prompt itself [somewhere over here](https://github.com/cenk1cenk2/listr2/blob/fed5da85190c89419fbdcd1d6213b8b6ce113762/src/utils/prompt.ts#L46).
- And check if the task prompt is an instance of enquirer in the skip function [here](https://github.com/cenk1cenk2/listr2/blob/fed5da85190c89419fbdcd1d6213b8b6ce113762/src/lib/task-wrapper.ts#L77).

I think this will somehow work out, but in the renderer, we also have to check task.prompt as well to render at the absolute bottom.

**Comment by AJHenry** [comment]
I think that approach could work, I'll play around with it

This isn't that urgent and I'll have time tomorrow to take a crack at it too

**Comment by cenk1cenk2** [comment]
Okay i gave it a try. It seems to be going well but I encountered a problem with enquirer itself. Even though enquirer is an event emitter and looking at the code should emit a 'prompt' message when it initiates a prompt it does not fire the eventlistener [here.](https://github.com/cenk1cenk2/listr2/blob/79ba2bb2005a3d646c9e5fafc1347fdc4a369cc7/src/utils/prompt.ts#L48)

Did you managed to get something out of `enquirer.on('prompt')`.

**Comment by AJHenry** [comment]
I too ran into that problem and I had to pass in an enquirer instance via `injectWrapper` and only use the event listener in the same scope as where `.prompt` is called. 

Could we just destroy the enquirer instance once the task is skipped? We can then just clear the bottom bar and reinitialize enquirer if a new prompt comes up later

**Comment by AJHenry** [comment]
I was also exploring the idea of a `cancelPrompt` function that would be exposed by TaskWrapper where it sets `this.task.prompt` to false and unbinds the instance of `this.createPrompt`

**Comment by cenk1cenk2** [comment]
What do you think of normally skipping the task or throwing out an error canceling the active prompt? I never invoke constructor of enquirer that should be why.

**Comment by AJHenry** [comment]
For me, I think if the prompt actually throws an error (via CTRL-c or invalid input) it should bubble up to the task. However, if a task cancels a prompt via skip or cancelPrompt, it should not throw an error

**Comment by cenk1cenk2** [comment]
Yeah I agree on that part as well. 

If ctrl-c -> error
via skip or cancelledprompt or such -> no error, just carry on

**Comment by AJHenry** [comment]
I think the best approach would be to create a cancelPrompt func for the task itself. That way we can expose that function to the user as well, and `skip` could implicitly call it

**Comment by cenk1cenk2** [comment]
But I have to also handle skip and on errors with exitOnError: false since this is kind of a bug by itself.

**Comment by AJHenry** [comment]
Ah ok, that makes sense

**Comment by cenk1cenk2** [comment]
But you want to skip only the prompt not the task itself, I understand your thinking as well. But the problem might be I have to save the prompt to task.prompt to later access it and cancel it.

**Comment by AJHenry** [comment]
Yea that was one of my ways of solving this, that way we can tackle cancelling the prompt on skip and giving users the option to also cancel a prompt during an active task. 

But bubbling up errors might be difficult in that case

**Comment by cenk1cenk2** [comment]
Can you give a try to [this branch](https://github.com/cenk1cenk2/listr2/tree/issue/173).

The last thing about canceling the prompt is missing but and it uses prompt.submit() instead of prompt.cancel() because cancel throws out an error even though I try to catch it.

**Comment by AJHenry** [comment]
Sure I can give it a crack today. However, while I was playing with it yesterday in my core project, I ran into an issue. After I cloned, built, and `npm linked` the project, no matter what I did, the enquirer prompt would not display using my locally built package. 

I'll try and figure out how to get the examples to build today though

I'll put together a contributing guide while I'm at it

**Comment by cenk1cenk2** [comment]
This should work for examples, no need to build them if I get you correctly.
```shell
yarn example examples/get-user-input.example.ts
```

If you install all the dependencies as you did to build the project, I think linking should work but enquirer is not installed as production dependency. So I am not sure what went wrong.

The easier way of doing this is running the docker-compose stack and linking the package to your project via npm. Since it will recompile on changes.

**Comment by AJHenry** [comment]
I'm not sure what happened with enquirer either, I installed it on both projects just to make sure but no avail, perhaps it needs to be installed globally when linking? I know npm link sets symlinks through .nvm node_modules so I'll try that next

Thanks for the setup, I can take a look at this later today and report back

**Comment by AJHenry** [comment]
I was running into the issue with cancelling the prompt too since enquirer always returns an error and [doesn't differentiate between a SIG or programmatically running cancel](https://github.com/enquirer/enquirer/blob/8d626c206733420637660ac7c2098d7de45e8590/lib/prompt.js#L150). I'm fine with leaving it as submit for now.

I added a function `cancelPrompt` that is exposed to the task and can be used to cancel a task with or without an error, on [this branch](https://github.com/AJHenry/listr2/tree/add-prompt-cancel)

Let me know if this works for you and I'll write some tests for it

**Comment by cenk1cenk2** [comment]
Everything seems where it should be, but don't you think that utilizing task.prompt is better instead of creating a new prompt instance variable, or was that not possible?

**Comment by AJHenry** [comment]
Thats a good point, let me change some types around and we could use that

**Comment by cenk1cenk2** [comment]
Amazing. I want to thank you for this contrubition and while this is added we had the chance to fix a bug on the way. 

If you can create a pull request when it is read I will merge it tommorow.

**Comment by AJHenry** [comment]
Sounds good! And happy to help, this project is a a core package for one of my projects so you'll definitely see me contributing again soon (I really gotta add an option for line wrapping in the default renderer)
