### ISSUE TITLE
No valid exports for `listr2/node_modules/uuid`

### ISSUE THREAD

**Issue by IgnusG** [cenk1cenk2/listr2#25]
Running lint-staged (using listr2 2.0.1 https://github.com/okonet/lint-staged/blob/master/package.json#L41) fails when running with the following stack:
```
husky > pre-commit (node v13.3.0)
internal/modules/cjs/loader.js:621
  throw e;
  ^

Error: No valid exports main found for 'project/node_modules/listr2/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (project/node_modules/listr2/dist/lib/task.js:9:16)
    at Module._compile (internal/modules/cjs/loader.js:1128:30) {
  code: 'MODULE_NOT_FOUND'
}
husky > pre-commit hook failed (add --no-verify to bypass)
```

I've tried removing `node_modules` and package-lock and re-installing but no luck 😔

**Comment by IgnusG** [comment]
@cenk1cenk2 Any Idea what could be going wrong?

My node version is locked at v13.3.0

lint-staged is latest [10.2.3](https://github.com/okonet/lint-staged/releases/tag/v10.2.3)
husky is latest [4.2.5](https://github.com/typicode/husky/releases/tag/v4.2.5)

**Comment by cenk1cenk2** [comment]
There seems to be a similar problem in another library:
https://github.com/strongloop/loopback-next/issues/5381

I will roll back to the previous version of UUID, let us see if that fixes it.

**Comment by cenk1cenk2** [comment]
Hope rollback to the prior version solves this issue because this was not really an issue in prior versions. I can not also seem to recreate it with node13, that is the interesting part. But "uuid" is only used to generate random task ids, so I can swap it for anything else if the issue persists.

**Comment by cenk1cenk2** [comment]
This is the base issue: 
https://github.com/uuidjs/uuid/issues/428

**Comment by iiroj** [comment]
@cenk1cenk2 The package nanoid is a pretty popular option, especially if the id doesn't have to be an official UUID: https://github.com/ai/nanoid

**Comment by cenk1cenk2** [comment]
I can replace that because uuid is a bit overkill. Just had to create some random ideas even math.random should have worked but while initially integrated it i just used that it stayed like it.
