### ISSUE TITLE
Provide a way to run some code after the inner list finshes working

### ISSUE THREAD

**Issue by erykpiast** [cenk1cenk2/listr2#257]
I've tried to simply `run` and `await` the inner `Listr` instance, but then the UI breaks.

```javascript
new Listr([/* ... */, {
    title: 'Some task with inner list',
    task: async (_, task) => {
        try {
            await task.newListr([/* some tasks, one of them might fail */], {
                concurrent: true
            }).run();

            task.title += ' (success)';
        } catch (err) {
            task.title += ' (failed)';
            // plus some cleanup logic, to restore state of things before
            // the whole process started
        }
    }
}], {
    exitOnError: false,
});
```

https://user-images.githubusercontent.com/1434406/104372862-65ca4000-5520-11eb-9fee-db9c58874480.mp4

The repository with code producing above: https://github.com/erykpiast/listr2-callback

**Comment by cenk1cenk2** [comment]
I will have a crack at it now i understand the problem more clearly. Initially i thought that we can use an option for stdout and pass in task.stdout() of outer task to inner task of that option but that wont look good. The behaviour is normal because log update package gets the whole priority of process.stdout so inner task tries to overwrite outer task output and vice versa. But there should be a solution to this with the current code base, if not i will try to add something to overcome it. Thank you for your time on the reproduction of the issue.

**Comment by erykpiast** [comment]
Thank you for your will to help!

**Comment by cenk1cenk2** [comment]
Sorry, I have been swamped with work this week, only had proper time today.

I have thought that adding another entity to a task named `rollback` would be the best way to handle errors/rollback actions for subtasks. Looking at your code it covers mostly what you want to do and think that it would be a useful addition for lots of subtasks with a cleanup process if any fails, providing alternative ways to try/catch blocks even.

It goes something like this. So any task can have a `rollback` function which gets basically the same input as the task itself. But if you have subtasks to your parent task, and write the `rollback` function to the parent, if any of the subtasks will fail, the parent will execute a function trying to roll back what has been done with the custom logic.

Still have somethings more to figure out, add readme and tests then I will publish it in the beta channel if this solution suffices your problem, but I think it covers it.

Looks like this
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/26881592/104848781-ab06bd00-58e6-11eb-8899-e88f8240b2db.gif)

```typescript
  // 4SIhMkI14b8s2hW1esiORoa1UINGHwAr
  logger.start('This would trigger the onError functionality if the parent task fails.')

  task = new Listr<Ctx>(
    [
      {
        title: 'Something with rollback.',
        task: (ctx, task): Listr =>
          task.newListr(
            [
              {
                title: 'This task will fail.',
                task: async (): Promise<void> => {
                  await delay(2000)
                  throw new Error('This task failed after 2 seconds.')
                }
              },
              {
                title: 'This task will execute.',
                task: (ctx, task): void => {
                  task.title = 'I will change my title if this executes.'
                }
              }
            ],
            { exitOnError: true }
          ),
        rollback: async (ctx, task): Promise<void> => {
          task.title = 'I am trying to rollback stuff, previous action failed.'

          await delay(1000)

          task.title = 'Doing something other than this.'

          await delay(1000)

          task.title = 'Some actions required rollback stuff.'
        }
      }
    ],
    {
      concurrent: false,
      exitOnError: true
    }
  )

  try {
    const context = await task.run()
    logger.success(`Context: ${JSON.stringify(context)}`)
  } catch (e) {
    logger.fail(e)
  }

  // vnT6mmZ5GtNqgXaPHqXxTIpDm5sltAZx
  logger.start('Rollback in normal task.')

  task = new Listr<Ctx>(
    [
      {
        title: 'Something with rollback in the subtask itself.',
        task: (ctx, task): Listr =>
          task.newListr(
            [
              {
                title: 'This task will execute.',
                task: async (): Promise<void> => {
                  await delay(1000)
                }
              },
              {
                title: 'This task will fail.',
                task: async (): Promise<void> => {
                  await delay(2000)

                  throw new Error('This task failed after 2 seconds.')
                },
                rollback: async (ctx, task): Promise<void> => {
                  task.title = 'I am trying to rollback stuff, previous action failed.'

                  await delay(1000)

                  task.title = 'Doing something other than this.'

                  await delay(1000)

                  task.title = 'Some actions required rollback stuff.'
                }
              }
            ],
            { exitOnError: true }
          )
      }
    ],
    {
      concurrent: false,
      exitOnError: true
    }
  )

  try {
    const context = await task.run()
    logger.success(`Context: ${JSON.stringify(context)}`)
  } catch (e) {
    logger.fail(e)
  }
```

**Comment by cenk1cenk2** [comment]
Please check out the latest beta and tell me what you think. I will later merge it to the upstream branch.

**Comment by erykpiast** [comment]
Thank you @cenk1cenk2! This addition looks promising, I'll test it out and let you know. Thanks again!
