### ISSUE TITLE
No valid exports main found for 'listr2/node_modules/nanoid'

### ISSUE THREAD

**Issue by iiroj** [cenk1cenk2/listr2#28]
It was reported in https://github.com/okonet/lint-staged/issues/870 that using Node.js version **13.6.0** listr2 fails to a nanoid import. The issue affects lint-staged because of the semver range allowing `listr@2.0.3` to be installed. I assume this error is similar to https://github.com/cenk1cenk2/listr2/issues/25

**Comment by iiroj** [comment]
I wonder if https://github.com/ai/nanoid/issues/205 is related.

**Comment by iiroj** [comment]
I think what would be good for `listr2` is to go through its dependencies engines declarations, and match the Node.js requirement.

For example, nanoid currently declares Node.js versions `^10 || ^12 || >=13.7`, which would imply the same requirements for listr2 as well.

**Comment by cenk1cenk2** [comment]
This problen with random id generation is interesting. I do not want to limit node version with a trivial dependency as this maybe it should be best to go back to working version of ^7 of uuid

**Comment by cenk1cenk2** [comment]
And will add 13.6 to tests implicitly to catch this error. Might be the best workaround.
