### ISSUE TITLE
exitOnError swallows output

### ISSUE THREAD

**Issue by sarink** [cenk1cenk2/listr2#295]
According to the docs:
>   // it will collect all the errors encountered if { exitOnError: false } is set as an option
>  // elsewise it will throw the first error encountered as expected

In practice:
```
  new Listr(
    [
      {
        title: 'fail',
        task: () => {
          throw new Error('fail');
        },
      },
    ],
    { exitOnError: false }
  )
    .run()
    .catch((e) => console.error('in catch', e))
```
If `exitOnError: false` is set, the `catch` is never triggered.

**Comment by cenk1cenk2** [comment]
This is the intended behaviour, matching the original Listr and what I also prefer too.  I guess there is no way unless I throw all the errors after, which is undesirable for most cases.

You can use the `task.error`, if you want to access the catcher error, even it is `exitOnError: false`.

https://github.com/cenk1cenk2/listr2#throw-errors
```
const task = new Listr(...)
logger.fail(task.err)
// will show all of the errors that are encountered through execution
```

**Comment by sarink** [comment]
Got it, that makes sense. Perhaps the only thing to do is to update this part of the README, which suggests that listr _will_ re-throw
```
try {
  await tasks.run()
} catch (e) {
  // it will collect all the errors encountered if { exitOnError: false } is set as an option
  // elsewise it will throw the first error encountered as expected
  console.error(e)
}
```

**Comment by cenk1cenk2** [comment]
Yes, it may need an update. But I am planning to create a documentation site because README is getting much bigger than I want for node_modules.
