### ISSUE TITLE
Elapsed time for verbose renderer

### ISSUE THREAD

**Issue by shumkov** [cenk1cenk2/listr2#320]
It would be really helpful to have the `elpasedTime` option in the verbose renderer to display how much time tasks took.

**Comment by cenk1cenk2** [comment]
sure that would be easy to enable since functionality is already in place. i will take a look when i have extra time, hopefully this weekend.

**Comment by shumkov** [comment]
@cenk1cenk2 Sounds cool! Thank you.

**Comment by cenk1cenk2** [comment]
I added the appropriate example [here](https://github.com/cenk1cenk2/listr2/blob/19e8b14f275c0d754de1a37f1d1e0495fda68a31/examples/task-timer.example.ts#L77).  

This demonstrates how to use it while using verbose renderer as the fallback renderer but it should work either way. I just wanted to be sure that it does not collide with the `showTimer` option in the primary renderer.

**Comment by shumkov** [comment]
@cenk1cenk2 Thank you! It works as expected!
