### ISSUE TITLE
Confusion between `NumberPrompt` vs `Numeral`

### ISSUE THREAD

**Issue by grempe** [cenk1cenk2/listr2#325]
When trying to integrate Enquirer prompts for the first time It took some digging in your code to figure out how to get number prompts to work.

In your code you export a `Numeral` type.

https://github.com/cenk1cenk2/listr2/blob/1fbfaf27c2e3325855de73154689defabd679b0d/src/utils/prompt.interface.ts#L119

But in the enquirer docs they have a Markdown heading for a `Numeral` type (which is maybe where you got your naming from?) but the actual thing they export is a `NumberPrompt`:

https://github.com/enquirer/enquirer#numeral-prompt

I don't know why they have this confusion either.

Is it possible to help clear up the confusion to make this more discoverable? Or make `Number` an alias of `Numeral`? Perhaps also document here which types `Listr2` works with?

https://listr2.kilic.dev/general-usage/user-input

Thanks!

**Comment by grempe** [comment]
cc: @jonschlinkert

**Comment by cenk1cenk2** [comment]
I hope to not overwrite the types as soon as the merge request on the upstream merges. I only tried to convert the types that I was using at the time and added the rest mostly from the documentation, so it may be a little bit buggy. Sorry for that.

I might take a look this weekend if i have some extra time, but can not promise since currently bit swamped. a pull request is welcome if you have any extra time.

**Comment by jonschlinkert** [comment]
Hi, please read the readme. It is explained there.

**Comment by cenk1cenk2** [comment]
It seems numeral seems alright to use, looking at [here](https://github.com/enquirer/enquirer/blob/8d626c206733420637660ac7c2098d7de45e8590/index.js#L228) how prompt names are registered, and it is actually registered as `numeral`  in [here](https://github.com/enquirer/enquirer/blob/8d626c206733420637660ac7c2098d7de45e8590/lib/prompts/index.js#L19). I added an example [here](https://github.com/cenk1cenk2/listr2/blob/49e67a6c4385774790a1d83fb35bc4fdb4ea6d73/examples/get-user-input.example.ts#L42) but typescript should enforce the types when you write the `Numeral` as type.

I do not think that adding this to the readme would be any more helpful than enquirer readme itself. I intend to remove the types as soon as the merge request finalizes closing #235.
