### ISSUE TITLE
Execa streamed output support

### ISSUE THREAD

**Issue by MatissJanis** [cenk1cenk2/listr2#37]
Hey!

It would be very nice if listr2 would also have enquirer support just as the first version did. Currently it's possible to execute async commands and wait for them to complete, however **streaming the output** from them does not seem to be possible.

Example:
```js
{
  title: "List files",
  task: (ctx) => {
    return execa.command(" ls -lah . && sleep 10 && ls -lah .");
  }
}
```

The command will execute successfully, however the output will not be streamed. I tried a bunch of different variations as well, but none were successful. The output is not being streamed to the console.

Help here would be much appreciated!

**Comment by cenk1cenk2** [comment]
I will have a look at this early tomorrow afternoon. I think it is time to expand the tests.

**Comment by cenk1cenk2** [comment]
You might redirect the stdout of execa using task.stdout. i am not sure if execa.command returns a promise or a stream. But i will anyway rewrite the stream to output conversion.

**Comment by MatissJanis** [comment]
Piping to `task.stdout` works in terms of sending the output to listr, however then the problem is that any subsequent step is executed prior to the task finishing.

This might, however, be an `execa` issue. I ported some tasks to `shelljs` and it works.. not great, but much better. Provides the output and waits for the task to finish before proceeding.

```js
{
  title: "List files",
  task: (ctx, task) => {
    const subprocess = execa(" ls -lah . && sleep 10 && ls -lah .");

    subprocess.stdout.pipe(task.stdout);
    return subprocess;
  }
}
```
