### ISSUE TITLE
Icons doesn't work with cmd.exe

### ISSUE THREAD

**Issue by bokzor** [cenk1cenk2/listr2#385]
Hi,

As you can see in the picture, icons are not displaying correctly.

![image](https://user-images.githubusercontent.com/3626888/116707286-c9448480-a9ce-11eb-9c56-b888ee0ff74a.png)

This happened on a WIndows 10 machine with System32\cmd.exe

**Comment by cenk1cenk2** [comment]
Are you using a nerd fonts based font for cmd?

**Comment by bokzor** [comment]
I didn't change it.
It seems that 'Consolas' is used.

**Comment by cenk1cenk2** [comment]
Maybe you can try with https://github.com/wclr/my-nerd-fonts/blob/master/Consolas%20NF/Consolas%20Nerd%20Font%20Complete%20Mono%20Windows%20Compatible.ttf . I am not actually sure how the default command prompt behaves. But the icons are mostly directly dependent on https://www.npmjs.com/package/figures and even though it lists them as having windows defaults in practice it may not depending on the terminal.

**Comment by bokzor** [comment]
Strange. But icons frrom Oclif are working fine. See the first 'check'

**Comment by cenk1cenk2** [comment]
okay i have realized at some point i have changed it to use the unicode ones coming from nerd fonts everytime. i will add the windows defaults back if you are not using windows terminal or alacritty that may support it.

**Comment by cenk1cenk2** [comment]
Can you try the latest release, v3.8.2, and whether it solves your problem =?

**Comment by bokzor** [comment]
Yes it works. Thanks
