### ISSUE TITLE
Duplicate lines

### ISSUE THREAD

**Issue by bokzor** [cenk1cenk2/listr2#403]
When executing Listr2 on Windows 10 with PowerShell there are some lines that are duplicated.

Here is the code 

```
          const tasks = new Listr<any>([
            {
                title: 'Task1',
                task: () => jenkins.executeJobAndWaitForResultAsync(job)
            },
            {
                title: 'Task2',
                task: () => jenkins.executeJobAndWaitForResultAsync(job2)
            },

        ], {concurrent: false});

        tasks.run().catch((err) => {
            console.error(err);
        });
```

![image](https://user-images.githubusercontent.com/3626888/118468121-bc30d080-b704-11eb-9f93-4d3fa7aea824.png)

**Comment by cenk1cenk2** [comment]
Can you check #296 and #310 and ensure that nothing writes to stdout. I will swap out this log-update yet I have still not found the time.

**Comment by bokzor** [comment]
Hard to be sure what was the problem. But I think it's because of some 'console.log'.
