### ISSUE TITLE
breaking change on `rxjs` upgrade

### ISSUE THREAD

**Issue by CastileMan** [cenk1cenk2/listr2#409]
Hi, we notice the `rxjs` upgrade in version `3.8.3`, this could leading to some reference error if other modules import `rxjs@6`.  A breaking change is recommended if you guys need to upgrade `rxjs` to 7.

**Comment by cenk1cenk2** [comment]
Hello @CastileMan ,

I do not get why this is a concern, it is an internal dependency and if you explicitly list `rxjs` as project dependency it will just install another version inside the folder of the `listr2`. I am planning to drop `rxjs` in upcoming major release anyways.

Can you explain why this can cause a problem for you?

**Comment by CastileMan** [comment]
> Hello @CastileMan ,
> 
> I do not get why this is a concern, it is an internal dependency and if you explicitly list `rxjs` as project dependency it will just install another version inside the folder of the `listr2`. I am planning to drop `rxjs` in upcoming major release anyways.
> 
> Can you explain why this can cause a problem for you?

First, my project didn't rely on `rxjs` directly but though a third party vendor. So it doesn't make mense to explicitly list it as project dependency.
Second, `rxjs-compat` has imported `rxjs`, but `rxjs-compat` has not explicitly listed `rxjs` as project dependency eithor, so it will import the `rxjs@7` installed by `listr2`.
For these reasons, i think it might be a better decision to release a breaking change if you must upgrade `rxjs@6` to `rxjs@7`

**Comment by cenk1cenk2** [comment]
Okay. Thank you for the heads up, I just will roll it back to rxjs6 for now, since I am not really using rxjs for its features at the moment. The plan is to get rid of it completely.
