### ISSUE TITLE
Skip using async function not usable

### ISSUE THREAD

**Issue by pbelbin** [cenk1cenk2/listr2#411]
Not sure if this is just me not understanding how to do it, or, whether this is a bug.

I want to use an async function to provide the `skip` response, and have the ability to pass back either a string or a boolean, not just one or the other.

Both `string | boolean` can be provided when the function is used synchronously, but, not when used asynchronously.  In that case, it seems, only one or the other is allowed, not both.

From what I can see in the samples and documentation, This is fine:
```
			skip: (ctx): string | boolean => {
				if (Math.random() < 0.5) {
					return 'too low';
				}
				
				return false;
			},
```

However, as I mentioned, I need to make an async call to a function, and that's where it gets troublesome.

I do not see any async examples of this in the test class either!

Here is what I want to do, but this is not OK, apparently:
```
skip: async (ctx): Promise<string | boolean> => {
				if (Math.random() < 0.5) {
					return 'too low';
				}
				
				return false;
			},
```

I get this complaint:
```
Type '(ctx: never) => Promise<string | boolean>' is not assignable to type 'string | boolean | ((ctx: never) => string | boolean | Promise<boolean> | Promise<string>) | undefined'.
  Type '(ctx: never) => Promise<string | boolean>' is not assignable to type '(ctx: never) => string | boolean | Promise<boolean> | Promise<string>'.
    Type 'Promise<string | boolean>' is not assignable to type 'string | boolean | Promise<boolean> | Promise<string>'.
      Type 'Promise<string | boolean>' is not assignable to type 'Promise<boolean>'.
        Type 'string | boolean' is not assignable to type 'boolean'.
          Type 'string' is not assignable to type 'boolean'.ts(2322)
listr.interface.d.ts(40, 5): The expected type comes from property 'skip' which is declared here on type 'ListrTask<never, typeof DefaultRenderer>'
```

so, how is this done?

or, is it a bug?

I see that [this](https://github.com/cenk1cenk2/listr2/blob/f6d6d6f2e1ecb2bbe75b5ae610e8f2b10112ca1e/src/lib/task.ts#L35) shows there is no response type allowed of `Promise<string | boolean>`, only `Promise<string> | Promise<boolean>` among the options.

**Comment by cenk1cenk2** [comment]
Thank you again for the contribution and your time.

**Comment by pbelbin** [comment]
You're welcome.  Thank you for taking care of it! :)
