### ISSUE TITLE
Add to Deno ?

### ISSUE THREAD

**Issue by phonglk** [cenk1cenk2/listr2#426]
Can we add this lib to deno please?
https://deno.land/x#info

**Comment by cenk1cenk2** [comment]
Unfortunately, it would be hard for me to maintain a deno package.  I am open to pull requests but I can not see how this can be easily done since deno has a completely different import structure as in the golang as well as some packages that this package relies on is not ported to the deno.

**Comment by phonglk** [comment]
I see, thank you for your response.
