### ISSUE TITLE
Access context after run

### ISSUE THREAD

**Issue by sarink** [cenk1cenk2/listr2#427]
Some of my tasks perform operations, like connecting to a database, and that db connection is stored on the `context`.

Regardless of if the pipeline succeeds or fails, whenever it's all finished, I need to close these connections.

I know that if run _succeeds_ , `ctx` will be the first argument `listr.run((ctx) => { ctx.db.close(); }` would work fine. But how do you handle the case where it fails? `listr.run().catch((err) => { // how to get ctx here?`

Ideally for my case, it would be available on the `listr` object itself, so I could use it in `finally` (although, I would also settle for something like `listr.run(closeConn).catch(closeConn)`

I was expecting this to work, but it looks like `listr.options.ctx` is `undefined`
```
const listr = new Listr([
  {
    task: async (ctx) => {
      ctx.test = 'test';
      throw new Error('force error');
    },
  },
]);

listr.run().finally(() => {
  console.log('options.ctx', listr.options?.ctx);
});
```

Any ideas?

**Comment by cenk1cenk2** [comment]
Unfortunately `listr.options.ctx` is just a jumper to write the context into the local function that can be seen [here](https://github.com/cenk1cenk2/listr2/blob/50b58d13f9488980a1c146ca718c74f1b0525d60/src/listr.ts#L112). In the case of errors it is stored in the class itself that can be seen [here](https://github.com/cenk1cenk2/listr2/blob/50b58d13f9488980a1c146ca718c74f1b0525d60/src/listr.ts#L25). This can be accessed afterward in the case of [error collection](https://listr2.kilic.dev/general-usage/handling-errors#error-collection-badgev200badge).

We can move the context into the class itself then it should be easily accessible like the collected errors. I just wonder that whether it would be a performance hit but anyways it should be a negligable one.

**Comment by cenk1cenk2** [comment]
One quick question if you create your context object outside and pass it thorugh run or options.ctx doesnt the tasks mutate the object?

**Comment by sarink** [comment]
Hmm, yes it does. Are you suggesting something like
```
type ListrContext = { dbClient: MongoClient };
const ctx = {} as ListrContext;
const listr = new Listr<ListrContext>([
  {
    title: 'Connect to db',
    task: (ctx) => ctx.client = await MongoClient.connect(...);
  }
]);
listr.run(ctx).finally(() => ctx.close());
```
That does work, although, the entire concept of context is kind of pointless then, isn't it? I could just keep all the context variables outside and not use listr's context, I suppose.

**Comment by cenk1cenk2** [comment]
The errors collected have a snapshot of the context object, which can be seen [here](https://github.com/cenk1cenk2/listr2/blob/50b58d13f9488980a1c146ca718c74f1b0525d60/src/interfaces/listr-error.interface.ts#L2). But it is an array since not-failing errors are also collected.

If we add a similar approach it would be like this, which is not much different than taking the context outside. But I see your point, it does not make much of a sense.
```typescript
const tasks = new Listr({})

try {
  await tasks.run()
} catch {
  // as in the tasks.err
  await tasks.ctx.closeConnection()
}

```

With the current error structure you can have the last error therefore the context as follows:
```typescript
const tasks = new Listr({})

try {
  await tasks.run()
} catch {
  // as in the tasks.err
  await tasks.err.pop().context.closeConnection()
}

```

**Comment by sarink** [comment]
I see, so something like this could work
```
const listr = new Listr<ListrContext>([
  {
    title: 'Connect to db',
    task: (ctx) => ctx.client = await MongoClient.connect(...);
  }
]);

const closeConn = (ctx: ListrContext) => ctx.client.close();

listr
  .run()
  .then(closeConn)
  .catch(() => closeConn(listr.err[0]?.context));
```

**Comment by sarink** [comment]
I guess I'll also need to collect and re-throw the errors then, right?

**Comment by cenk1cenk2** [comment]
It might not be the first error but it should be the last, if it stops so you can `pop()` it out. The rethrowing of the error should be fine.

```typescript
listr
  .run()
  .then(closeConn)
  .catch((e) => { 
    closeConn(listr.err.pop().context) 
    throw e
  });
```

But I still think that creating a mutatable object is a bit more clean, even though the context is outside.

**Comment by sarink** [comment]
Is there any way to keep the context on the `listr` object itself?

**Comment by cenk1cenk2** [comment]
Yes exactly. That is one of my offers if you want we csn do that too. I am just not sure would it be a unnecassary overhead or not.

**Comment by sarink** [comment]
Since it's just an object _reference_, I don't think it would impact performance in any way. The context is already being held in memory, this would just be a little shortcut/pointer to it.

**Comment by cenk1cenk2** [comment]
That is also true. For recurring subtasks it should be pretty much the same. I will add this in a couple of hours. Thank you.

**Comment by cenk1cenk2** [comment]
https://listr2.kilic.dev/getting-started/the-concept-of-context#as-class-object
