### ISSUE TITLE
Observable tasks skip entirely with no errors

### ISSUE THREAD

**Issue by acidjazz** [cenk1cenk2/listr2#453]
I have this odd issue in some environments where any task that returns an Observable skips that task completely w/out any errors.

Any tips or recommendations on how I should approach this issue? if I run the tasks inside the Observable separately it works perfectly fine.

**Comment by cenk1cenk2** [comment]
hello @acidjazz ,

can you give a bit more clearer explanation or provide a reproducible example?

**Comment by acidjazz** [comment]
@cenk1cenk2 It's a very difficult one still - it's only certain versions of node - only duplicatable on OSX so far - all tasks that return an Observable Just simply complete w/out running any code in the observable.

So far its duplicatable by installing `v0.1.27` of the tool I use listr2 with - fume-cli:

https://github.com/fumeapp/fume-cli

Steps to reproduce

1. Create a fume account (https://fume.app) and connect any AWS account (all resources generated can be removed when done)
2. When installing the fume-cli, be sure to specify the older version
3. Run a `fume deploy` and the `upload()` task observable will skip completely, then it will fail since no file was sent.
4. If you comment out the observable part of `upload()` then the `deploy()` task will skip as well


If you install the latest `v0.1.31` i've stripped observables from the tasks and it should deploy fine - I have no idea why it's doing this since all code being run inside has no errors.

**Comment by cenk1cenk2** [comment]
I just have one idea which is rxjs 7 vs rxjs 6. I wanted to drop rxjs from this repo so I have not updated it. And somebody using it as a dependency also did not wanted that upgrade. I said okay since my plan is to remove that unnessary dependency.

**Comment by acidjazz** [comment]
@cenk1cenk2 Is it better maybe to then just use `task.title =` instead of having the observable report back? is there any other way to finish a task with a callback?

**Comment by cenk1cenk2** [comment]
`observer.complete()` is the actual callback as in the observable but I have seen that part you have already covered, so me saying this shows how clueless I am at the moment, forgive me. But other than that there is no direct callback from `task` to finalize the task itself. I do not get the question about `task.title`, I guess you can still access that stuff on the observable but it has not much to do with the finalization of the task.   

is these two are your function because there is some more deploy tasks going on, naming scheme confused me a little.
https://github.com/fumeapp/fume-cli/blob/6c9aa9c8ce7d1cfd8cb0789304c6cb797b58a716/src/lib/deploytasks.ts#L471
https://github.com/fumeapp/fume-cli/blob/6c9aa9c8ce7d1cfd8cb0789304c6cb797b58a716/src/lib/deploytasks.ts#L408

**Comment by acidjazz** [comment]
Basically I was using observables to update the title and have a task end via a callback, and since I've been having so many issues with it - My question now is: Is it at all possible to end a task via a callback w/out using observables?

**Comment by cenk1cenk2** [comment]
If you are not using observables yes. But you dont need a callback at all if the function finalizes it will end the task and can change the title via task wrapper.

**Comment by acidjazz** [comment]
@cenk1cenk2 Are you sure? even if i'm using async tasks that fire off a complete when they're done, like this:

https://github.com/fumeapp/fume-cli/blob/6c9aa9c8ce7d1cfd8cb0789304c6cb797b58a716/src/lib/deploytasks.ts#L421-L446

How then does it know it's complete?

**Comment by cenk1cenk2** [comment]
This is how it handles different cases https://github.com/cenk1cenk2/listr2/blob/1b62065cbae84797a33abfb91884da999cc46644/src/lib/task.ts#L206 . Just awaits it, if it is a function. So, yes you don't have to use observables, I usually use async functions all the time

**Comment by acidjazz** [comment]
OK: so re-factoring of the upload task, it doesn't seem to wait for `S3.ManagedUpload` 

```ts
  async upload(task: ListrTaskWrapper<any, any>, type: PackageType) {
    if (type === PackageType.code) await this.deployment.update('UPLOAD_CODE_ZIP')
    const sts = await this.deployment.sts()
    return new S3.ManagedUpload({
      service: new S3(sts),
      params: {
        Bucket: this.deployment.s3.bucket,
        Key: type === PackageType.layer ? this.deployment.s3.layer : this.deployment.s3.code,
        Body: fs.createReadStream(this.deployment.s3.paths[type]),
      },
    }).on('httpUploadProgress', event => {
      task.title = `${numeral((event.loaded / event.total)).format('0%')}`
    }).send(async (error: any) => {
      if (error) {
        await this.deployment.fail({
          message: error.message,
          detail: error,
        })
      }
    })
  }
```

What am i doing wrong here?

**Comment by acidjazz** [comment]
Same with the async task I was using with observers:

```ts
  async sync(task: ListrTaskWrapper<any, any>, folder: string, bucket: string, status: string) {
    await this.deployment.update(status)
    const sts = await this.deployment.sts()
    const client = require('@auth0/s3').createClient({s3Client: new S3(sts)})
    const uploader = client.uploadDir({
      localDir: folder,
      deleteRemoved: true,
      s3Params: {
        Bucket: bucket,
        ACL: 'public-read',
        Prefix: '',
      },
    })
    uploader.on('progress', () => {
      if (!isNaN(uploader.progressAmount / uploader.progressTotal)) {
        const formatted = numeral(uploader.progressAmount / uploader.progressTotal).format('0.00%')
        task.title = `${formatted} complete`
      }
    })
  }```

**Comment by acidjazz** [comment]
> OK: so re-factoring of the upload task, it doesn't seem to wait for `S3.ManagedUpload`
> 
> ```ts
>   async upload(task: ListrTaskWrapper<any, any>, type: PackageType) {
>     if (type === PackageType.code) await this.deployment.update('UPLOAD_CODE_ZIP')
>     const sts = await this.deployment.sts()
>     return new S3.ManagedUpload({
>       service: new S3(sts),
>       params: {
>         Bucket: this.deployment.s3.bucket,
>         Key: type === PackageType.layer ? this.deployment.s3.layer : this.deployment.s3.code,
>         Body: fs.createReadStream(this.deployment.s3.paths[type]),
>       },
>     }).on('httpUploadProgress', event => {
>       task.title = `${numeral((event.loaded / event.total)).format('0%')}`
>     }).send(async (error: any) => {
>       if (error) {
>         await this.deployment.fail({
>           message: error.message,
>           detail: error,
>         })
>       }
>     })
>   }
> ```
> 
> What am i doing wrong here?

BTW in reference to this version where I can update the title based on progress, this currently works:

```ts
  async upload(type: PackageType) {
    if (type === PackageType.code) await this.deployment.update('UPLOAD_CODE_ZIP')
    const sts = await this.deployment.sts()
    await new S3.ManagedUpload({
      service: new S3(sts),
      params: {
        Bucket: this.deployment.s3.bucket,
        Key: type === PackageType.layer ? this.deployment.s3.layer : this.deployment.s3.code,
        Body: fs.createReadStream(this.deployment.s3.paths[type]),
      },
    }).promise()
  }
```
But I don't see how I can specify these callbacks any more.

**Comment by acidjazz** [comment]
Figured id out - plain old promises! 

```ts
  async upload(task: ListrTaskWrapper<any, any>, type: PackageType) {
    if (type === PackageType.code) await this.deployment.update('UPLOAD_CODE_ZIP')
    const sts = await this.deployment.sts()
    return new Promise((resolve, reject) => {
      new S3.ManagedUpload({
        service: new S3(sts),
        params: {
          Bucket: this.deployment.s3.bucket,
          Key: type === PackageType.layer ? this.deployment.s3.layer : this.deployment.s3.code,
          Body: fs.createReadStream(this.deployment.s3.paths[type]),
        },
      }).on('httpUploadProgress', event => {
        task.title = `${numeral((event.loaded / event.total)).format('0%')}`
      }).send(async (error: any) => {
        if (error) {
          await this.deployment.fail({
            message: error.message,
            detail: error,
          })
          reject(error)
        } else {
          resolve(true)
        }
      })
    })
  }```

@cenk1cenk2 I think the overall result of this issue is to maybe just not recommend rxjs/observables for stable and leaner reasons - since this can all be done w/ promises.

Happy to close this issue if you want - or you can keep it open as reminder to update the docs? Happy to help with that as well.

**Comment by cenk1cenk2** [comment]
Thank you very much. Yeah, the advised way is to use promises as possible. For keeping the compatibility with the original listr and since it does already have rxjs embedded for the library, observables are just an option.
