### ISSUE TITLE
Logging doesn't display the last log statement.

### ISSUE THREAD

**Issue by from-nibly** [cenk1cenk2/listr2#497]
when calling logger.<level>('message'); the last line you log doesn't appear in the output.

```ts
import { Listr, Logger } from 'listr2';

new Listr({
  title: 'this task',
  task: () => {
    const logger = new Logger({ useIcons: true });

    logger.start('hello there!');
    logger.data('testing 123');
  },
})
  .run()
  .then(() => console.log('done'));
```

output

```
⠋ this task
❯ hello there!
✔ this task
done
```

**Comment by from-nibly** [comment]
So I tried using `task.output = 'foobar';` but that doesn't seem to work...

```ts
import { Listr } from 'listr2';

new Listr({
  title: 'this task',
  task: task => {
    task.output = 'foobar';
    task.output = 'barfoo';
  },
})
  .run()
  .then(() => console.log('done'));

```

output

```
✔ this task
done
```

Is the output picked up via an async process?

**Comment by cenk1cenk2** [comment]
Yes, but it collapses after the task finishes. You can have the `persistentOutput` flag to keep the output after that particular task finishes as seen [here](https://listr2.kilic.dev/general-usage/showing-output#default-renderer).

**Comment by cenk1cenk2** [comment]
But it will always have the latest output, so the idea here is to not have proper logging but have something to show the user what the current status of that action is.

**Comment by from-nibly** [comment]
:man_facepalming: Just realized I wasn't using the task arg I was using the context arg.

**Comment by cenk1cenk2** [comment]
Anyways in the example you have provided, it will just show it momentarily then collapse it off.

**Comment by from-nibly** [comment]
Also just to be clear though. I was using the first positional argument which is the ctx argument not the task argument so I was actually just adding a string to the output property of the context, not setting the output to something.
