### ISSUE TITLE
Add ability to allow custom enquirer editors

### ISSUE THREAD

**Issue by IgnusG** [cenk1cenk2/listr2#5]
I'm currently using this function inspired by (copied from) the [prompt method](https://github.com/cenk1cenk2/listr2/blob/master/src/lib/task-wrapper.ts#L74-L92):
```javascript
   function createCustomPrompt(task, Prompt, options) {
     task.prompt = true;
     let buffer = Buffer.alloc(64);
  
     const outputStream = through((data) => {
       buffer += data;
  
       // eslint-disable-next-line no-control-regex
       const deleteMultiLineRegexp = new RegExp(/.*(\u001b\[[0-9]*G|\u0007).*/m);          12
       if (deleteMultiLineRegexp.test(buffer.toString())) {
         buffer = Buffer.alloc(64);
        } else {
          task.output = buffer.toString();
        }
      });

      Object.assign(options, { stdout: outputStream });
      return new Prompt(options);
    }
```

With for example the [enquirer-editor](https://www.npmjs.com/package/enquirer-editor) like this:
```javascript
import EditorPrompt from 'enquirer-editor';
import { Manager } from 'listr2';

const manager = new Manager();
manager.add({
  title: 'Editor',
  task: async (_, task) => {
    const prompt = createCustomPrompt(task, EditorPrompt, { type: 'editor', message: 'Please Fill' });
    const message = await prompt.run();
  }
})
manager.runAll();
```

This works quite well, I was just wondering, @cenk1cenk2 do you think there's a way to incorporate this into listr2 somehow?
Or maybe make the `prompt` method from `TaskWrapper` more versatile to accept custom prompt classes?

**Comment by cenk1cenk2** [comment]
Do you mean that like an ability to inject custom functions inside the TaskWrapper?

**Comment by IgnusG** [comment]
Maybe an optional last argument for `prompt` to accept custom [`newPrompt`](https://github.com/cenk1cenk2/listr2/blob/master/src/utils/prompt.ts#L77). [`createPrompt`](https://github.com/cenk1cenk2/listr2/blob/master/src/lib/task-wrapper.ts#L96) could forward it down. 

(I've omitted types and replaced some of the existing code with ... in the below snippets)

In [`utils/prompt.ts`](https://github.com/cenk1cenk2/listr2/blob/master/src/utils/prompt.ts):
```javascript
export function createPrompt(
  type,
  options, 
  {
    error = false, 
    makeNewPrompt = newPrompt // <- default to existing newPrompt or use whatever is passed down
  } = {}
) {
  return makeNewPrompt(type, options).on('cancel', () => {...})
}
```

In [`lib/task-wrapper.ts`](https://github.com/cenk1cenk2/listr2/blob/master/src/lib/task-wrapper.ts):
```javascript
public async prompt(
  type, 
  options, 
  CustomPrompt // <- can be used by createPrompt as custom class
) {
    ...
  Object.assign(options, { stdout: outputStream })
  return createPrompt.bind(this)(type, options, { 
    makeNewPrompt: (t, o) => new CustomPrompt({ type: t, ...o }) // Maybe default to merging type with options?
  })
}
```

```javascript
import EditorPrompt from 'enquirer-editor';

{ 
  task: async (_, task) => 
    task.prompt(
      'editor', // type (merge with options above?)
      { message: 'EDIT' }, // options
      EditorPrompt // CustomPrompt
    )
}
```

What do you think about this approach @cenk1cenk2?

**Comment by cenk1cenk2** [comment]
There will be no type checking in my solution but I am thinking something like the one below:
If you have better ideas please throw one away.

```typescript
  manager.add([
    {
      title: 'Something',
      task: (ctx, task): void => {
        task.extend('logThis')('string')
      }
    }
  ])

  try {
    ctx = await manager.runAll({ extend: { logThis: (string): void => { console.log(string) } } })
  // eslint-disable-next-line no-empty
  } catch (e){

  }
```

**Comment by IgnusG** [comment]
Mmm, not sure how this helps in using custom equirer prompts. Could you give me an example with an enquirer plugin when using `extend`?

**Comment by cenk1cenk2** [comment]
It is just custom prompts, I see. I got it wrong then. I thought you want to extend it with another function so you can access it through the tasks. I will have a look at this today, and hopefully make enquirer more exposed so that you can extend it with custom prompts, because it is a bit limited at the moment.

I thought that also extending the stdout through function so that it can be used anything that generates data periodically but maybe it is a task for later.

**Comment by cenk1cenk2** [comment]
So this seems like a good enough solution for me what do you think?

You pass the class of the EditorPrompt directly to the type section and pass the options in the same way.

 ```typescript
manager.add([
    {
      title: 'Custom prompt test',
      task: async (ctx, task): Promise<void> => {
        ctx.testInput = await task.prompt(EditorPrompt, {
          message: 'Please write a short bio of at least 3 lines',
          initial: 'Start writing!',
          validate: (response): boolean | string => {
            if (response.split('\n').length < 4) {
              return 'The bio must be at least 3 lines.'
            }
            return true
          }
        })
      }
    },
    {
      title: 'Dump',
      task: (ctx, task): void => {
        task.output = ctx.testInput
      },
      persistentOutput: true
    }
  ])

  try {
    ctx = await manager.runAll()
  // eslint-disable-next-line no-empty
  } catch (e){

  }
```

**Comment by cenk1cenk2** [comment]
I merged it with [v.1.3.7](https://github.com/cenk1cenk2/listr2/releases/tag/v1.3.7). But just tested basic functionality with the `example.ts` again, needs more testing.
