### ISSUE TITLE
Converting circular structure to JSON error

### ISSUE THREAD

**Issue by shumkov** [cenk1cenk2/listr2#538]
Hello,

First of all, thank you for the great product. It's pleasure to create fancy CLI output using it.

In recent versions, we faced a problem when an error happening in a listr task. If context contains objects with circular reference, another error throws by `JSON.stringify`:  `Converting circular structure to JSON`.

It goes from `cloneObject` function:
```
    at cloneObject (/~/Dash/dashmate/node_modules/listr2/dist/utils/general.js:8:28)
    at TaskWrapper.report (/~/Dash/dashmate/node_modules/listr2/dist/lib/task-wrapper.js:50:104)
    at Task.run (/~/Dash/dashmate/node_modules/listr2/dist/lib/task.js:266:29)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async /~/Dash/dashmate/node_modules/p-map/index.js:57:22
```

I would recommend to use lodash's `cloneDeep`  or alternatives instead of `JSON.parse(JSON.stringify)`.

**Comment by cenk1cenk2** [comment]
Yeah, makes a lot of sense that would cause problems.

I would rather drop that fully and not include the task in the error.

**Comment by shumkov** [comment]
In this case, it will be harder to figure out the context. I mean which task is failed and so on. But I'm not insisting, you decide ;)

**Comment by ejnshtein** [comment]
Hi!

We have functions that allow modifying tasks inside.
Functions return task bodies (so object with `title`, `task`, e.t.c.)

And so this error comes up.
