### ISSUE TITLE
Context clone during error collection is unreasonable slow with large contexts

### ISSUE THREAD

**Issue by marcelmeulemans** [cenk1cenk2/listr2#596]
After an upgrade to 3.13.4 I noticed that my builds (github actions) were timing out whenever one of my listr tasks fails. After some investigation I have tracked it down to the use of the clone library in the `cloneObject` function. My context object is fairly large because amongst other things I am storing the results of a webpack complilation, which can easily be multiple megabytes in size, in the context. The cloning of the context here https://github.com/cenk1cenk2/listr2/blob/master/src/lib/task-wrapper.ts#L58 is so slow that it causes my builds to timeout after 15m. I haven't checked why clone is so slow but a quick test switching to an alternative library (https://www.npmjs.com/package/rfdc) shows a x30 speed increase.

PR with unit test showing the issue and suggested improvement here: https://github.com/cenk1cenk2/listr2/pull/595

**Comment by cenk1cenk2** [comment]
Closed with pr thanks
