### ISSUE TITLE
Incorect behaviour with Promise.race

### ISSUE THREAD

**Issue by EvgenBabenko** [cenk1cenk2/listr2#611]
Hi, i have 2 promices (one with resolve after 2000ms, second with reject after 5000ms), but after resolved promise, listr is waiting for second promise, Process just stucking for 3000ms

listr2 - v3.11.0

```
import chalk from 'chalk';
import { Listr } from 'listr2';

const asyncDelay = (ms: number) => {
  return new Promise((resolve) => {
    setTimeout(() => {
      resolve(null);
    }, ms);
  });
};

const delay = (ms: number) => {
  return new Promise((_, reject) => {
    setTimeout(() => {
      reject(new Error('TIMEOUT'));
    }, ms);
  });
};

const tasks = new Listr([
  {
    title: 'generate files',
    task: async () => {
      await Promise.race([asyncDelay(2000), delay(5000)]);
    },
  },
]);

const main = async () => {
  try {
    await tasks.run();
  } catch (error: any) {
    // eslint-disable-next-line no-console
    console.log(chalk.red(`[CLI] ${error}`));

    process.exit(1);
  }
};

main();

```

**Comment by cenk1cenk2** [comment]
Hey @EvgenBabenko , 
That seems wierd because task is only a function that is called with passing the context and task wrapper in so that behaviour does not make much sense to me at this moment. Do you have any leads?

**Comment by EvgenBabenko** [comment]
I know that is weird, but after resolving 1 promise, the second promise has blocked full process
It can be more noticeble, if u change delay from 5000ms for example to 50_000ms

**Comment by EvgenBabenko** [comment]
sorry, the problem related to nodejs
https://github.com/nodejs/node/issues/37683

**Comment by cenk1cenk2** [comment]
Oh, that is okay. I am glad you have worked it out.
