### ISSUE TITLE
Property 'subscribe' does not exist on type 'Task<any, typeof VerboseRenderer>'

### ISSUE THREAD

**Issue by sambunting** [cenk1cenk2/listr2#628]
I'm trying to create a custom renderer by subscribing to updates from each individual task (A lot like how the [verbose renderer](https://github.com/cenk1cenk2/listr2/blob/master/src/renderer/verbose.renderer.ts) works).

However, I'm getting a type error of `Property 'subscribe' does not exist on type 'Task<any, typeof VerboseRenderer>'.`

So far, the only difference I have is that I'm using `ListrTaskObject` instead of `Task` - as when I try to import it - I get another error of `Module '"../node_modules/listr2/dist"' declares 'Task' locally, but it is exported as 'ListrTaskObject'.`

Checking in the code - it looks like the `Task` class extends `Subject<ListrEvent>` from rxjs. But it doesn't seem to pass through the `subscribe` method to `ListrTaskObject` somehow?

**Comment by cenk1cenk2** [comment]
It's interesting, it just was exposed with another name to keep the compatibility with the older versions. I will investigate and get back to you but I guess earliest will be the weekend unfortunately,

**Comment by sambunting** [comment]
That would me massively appreciated! Thank you!

**Comment by cenk1cenk2** [comment]
Can you try the latest version, it just should export the types now.

If it is not solved nor a problem for you can you share your custom renderer.

**Comment by cenk1cenk2** [comment]
Okay, if this is in improvement it might be also related to the build methodology with tsup. Please give me feedback if it still fails because subscribe should be there since it extends Subject from rxjs.

**Comment by sambunting** [comment]
Will do! Thank you for taking a look at it! 😃

**Comment by sambunting** [comment]
_Actually_.... I think I've found the issue.... My version of VS Code is out of date quite a bit - and the ESLint Extension doesn't seem to be working all that well with the latest releases of ESLint.

Updating VS Code to the latest version of 1.63 has made the linting errors go away!

From my case - everything is working great, and this ticket is closed - thank you so much for looking into it, I massively appreciate it!!

**Comment by cenk1cenk2** [comment]
Yey that is great news. Good to hear. Cheers.
