### ISSUE TITLE
rxjs types used in TypeScript declaration but aren't shipped as a dependency

### ISSUE THREAD

**Issue by AndrewLeedham** [cenk1cenk2/listr2#632]
Hi, after upgrading to TypeScript@next I started getting the following error:
```
error TS7016: Could not find a declaration file for module 'rxjs'. '<redacted>/node_modules/listr2/node_modules/rxjs/dist/cjs/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/rxjs` if it exists or add a new declaration (.d.ts) file containing `declare module 'rxjs';`

1 import { Observable, Subject } from 'rxjs';
                                      ~~~~~~
```
(Not sure what changed in TypeScript@next that would cause this, but the error seems legitimate)
It would seem to me that `index.d.ts` relies on `rxjs` typings and `@types/rxjs` is not included as a dependency. I can workaround it by installing `@types/rxjs` myself, but it seems like it should be added to the `listr2` dependencies?

**Comment by AndrewLeedham** [comment]
Actually upon further investigation `@types/rxjs` does not exist, seems like an issue with how `rxjs` types are resolved in an ESM environment.

**Comment by cenk1cenk2** [comment]
Yes, rxjs is a Typescript project so it would be weird if it did not include the types. Do you have the problem still or is it solved by some configuration?

**Comment by AndrewLeedham** [comment]
Looks like ESM looks for types differently. Potentially an issue on rxjs's end, so I'll raise an issue over there.
