### ISSUE TITLE
Dynamically creating tasks

### ISSUE THREAD

**Issue by cfanoulis** [cenk1cenk2/listr2#643]
Ello! I have a task that firsts captures a list of URLs, then another tasks that would use said list of URLs to dynamically create a list of tasks to run. Is that possible? From my limited testing, the following: 

<details>
<summary>Show code:</summary>
```ts
const listr = new Listr<{ outdir: string; urls: string[]; }>([
	{
		title: 'Fetch URLs',
		task: async (ctx) => {
			ctx.urls = await getURLsSomehow();
		}
	},
	{
		title: 'Use URLs',
		task: async (ctx, task) => {
			task.newListr(
				ctx.urls.map((url) => ({
					title: `Using ${url}`,
					task: () => worker({ url, taskCtx: task }) // this returns a promise that resolves once the job is done
				}))
			);
		}
	}
]);
```
</details>

doesn't dynamically create tasks

**Comment by cenk1cenk2** [comment]
Hi @cfanoulis ,
Unfortunetly I will be away for a while with no real way to debug this.

You can checkout the code from below for generating the tasks dynamically in the meantime. Hope it helos
https://github.com/tailoredmedia/backend-nx-skeleton/blob/63e0ead4662039c6eb356ad392b7e1b1bd4f1209/packages/brownie/src/helpers/node.helper.ts#L19

**Comment by cenk1cenk2** [comment]
I see that you are not returning the task.newListr as result. That can be your problem if I can read it through the phone correctly.

**Comment by cenk1cenk2** [comment]
I would close this issue, since I do think it is solved after returning the task itself.
