### ISSUE TITLE
Compile errors when using TypeScript 4.8.2

### ISSUE THREAD

**Issue by Baune8D** [cenk1cenk2/listr2#653]
Im seeing the following errors when updating to TypeScript 4.8.2. Works fine with TypeScript 4.7.4

<img width="1526" alt="Screenshot 2022-08-29 at 14 04 59" src="https://user-images.githubusercontent.com/30204280/187197351-5e50b0ff-468f-4b9c-85e3-6c62a5d8d935.png">

**Comment by cenk1cenk2** [comment]
Hey @Baune8D,

Thank you for the bug report, this issue should be gone with the latest release.

Have a very nice day.
