### ISSUE TITLE
how to change spinner style?

### ISSUE THREAD

**Issue by thilllon** [cenk1cenk2/listr2#658]
It is my first time to use `listr2` and after struggling with documents, I can't find how to change spinner style.
Is there any way to change the spinner style?
https://listr2.kilic.dev/renderers/introduction

Thanks

**Comment by cenk1cenk2** [comment]
Unfortunetly this is not possible at this point but could easily be implemented through getting it as a renderer option.

 https://github.com/cenk1cenk2/listr2/blob/37244055fea0f45d9d5f419e7203ff2cb2815695/src/renderer/default.renderer.ts#L162

I suppose coloring is a different case which should be thought about.

**Comment by cenk1cenk2** [comment]
This should be available through v6 now.
