### ISSUE TITLE
Descendant tasks should also be rendered when all subtasks have no title

### ISSUE THREAD

**Issue by grtan** [cenk1cenk2/listr2#663]
![image](https://user-images.githubusercontent.com/11453989/222149285-f2d4361d-1e2f-49c4-a996-865984398715.png)

```js
const {Listr} = require('listr2')

function check(name, parentTask) {
  return new Listr({
    title: `check task ${name}`,
    task(ctx, task) {
      // do check
    },
  }, {}, parentTask)
}

const tasks = new Listr([
  {
    title: 'check',
    task: (ctx, task) => task.newListr([
      {
        // I must set the title, it will work fine
        // title: 'xxx',
        task: (ctx, task) => check(1, task.task),
      },
      {
        task: (ctx, task) => check(2, task.task),
      },
      {
        task: (ctx, task) => check(3, task.task),
      },
    ], {
      concurrent: true,
    }),
  },
  {
    title: 'check result',
    task: async (ctx, task) => {
      // do something
    },
  },
],  {
  rendererOptions: {
    collapse: false,
  },
})

tasks.run()
```

The console print as below, but I want to print the title of  check's children task.  How can i print `check task 1`, `check task 2`, `check task 3` currently?
![image](https://user-images.githubusercontent.com/11453989/222151132-ba37fec5-cf00-4def-8496-dfcb11d4208e.png)

**Comment by cenk1cenk2** [comment]
Hello @grtan,

Yeah I suppose that part should be removed. I do not remember exactly what that was for but I assume that it might be breaking compatability when removed.

**Comment by grtan** [comment]
@cenk1cenk2 Any plans for the future? If it cannot be removed uniformly, is it possible to customize the configuration in rendererOptions?

**Comment by cenk1cenk2** [comment]
Sorry for the late reply, it has been hectic for me for quite some time. This seems to be breaking nothing in the current behavior. I suppose I have put that in to save some CPU cycles but it is not important since the renderer is not in its most efficient form, the new release should be published now.

https://gitlab.kilic.dev/libraries/listr2/-/pipelines/44355

**Comment by grtan** [comment]
> Sorry for the late reply, it has been hectic for me for quite some time. This seems to be breaking nothing in the current behavior. I suppose I have put that in to save some CPU cycles but it is not important since the renderer is not in its most efficient form, the new release should be published now.
> 
> https://gitlab.kilic.dev/libraries/listr2/-/pipelines/44355

Thanks for your work

**Comment by grtan** [comment]
@cenk1cenk2 Thanks for your work🎉
