### ISSUE TITLE
Add a "passthrough" renderer

### ISSUE THREAD

**Issue by tommy-mitchell** [cenk1cenk2/listr2#669]
I'm making a [CLI for Listr](https://github.com/tommy-mitchell/listr-cli) that makes it easy to run arbitrary commands as a Listr task using `execa`, and I'm trying to find a way to run the commands in a CI environment without the Listr event notifications.

For example, with `listr 'echo hello'`:

```diff
- "[STARTED] echo",
- "[TITLE] Running \"echo hello\"...",
- "[TITLE] echo",
- "[DATA] hello",
- "[SUCCESS] echo",
+ hello
```

At first I thought I could use the `SilentRenderer` and pipe `execa`'s output, but I didn't realize that the renderer just eats all output. I'd like to propose a `PassthroughRenderer` that just pipes `task.output` to `stdout` (or perhaps `stderr` as well), ignoring the other events.

**Comment by cenk1cenk2** [comment]
You can use the SilentRenderer for that just set silentCondition to true so in both cases TTY and non-TTY both it will use that renderer or renderer to 'silent'.

The output you provided shows verbose renderer.

If you want to pass execa output to DefaultRenderer you can assign the stdout of execa to task.stdout().

**Comment by cenk1cenk2** [comment]
https://github.com/tailoredmedia/backend-nx-skeleton/blob/master/packages/nx-tools/src/utils/logger/pipe-process-to-listr.ts

I seem to be doing it this way idk why but task.stdout should work just fine.

**Comment by tommy-mitchell** [comment]
I didn't realize that was the verbose renderer, that's the output I was getting in my tests so I just assumed it was some sort of fallback.

So this is how I should do it?

```js
import {isCI} from "ci-info";

const tasks = new Listr(commands.map(command => ({
	// ...
	task: async (ctx, task) => {
		if(isCI) {
			return execa(command).pipeStdout(task.stdout());
		}
		// ...
	},
})), {
	// ...
	rendererSilent: isCI,
});
```

This doesn't seem to work, but I can use `console.log` so my initial assumption was incorrect. Thanks for the help.

**Comment by cenk1cenk2** [comment]
For both cases, you can directly pipe the output stdout. Then the output would go through whether you are using default or verbose renderer but if you want always to implement your own logging system you can use the silent renderer and do so.

But in this case, you are disabling all the logging including the execa output wherever this condition of isCI is true.

I would just advise you to leave the silent renderer away and pass it for any case, and give it a try. As I understood it, it is the thing you actually want.

No worries!

**Comment by tommy-mitchell** [comment]
I want the regular default renderer output when `isCI` is false. Turns out my problem was configuration:

```js
import {isCI} from "ci-info";
import {$} from "execa";

const tasks = new Listr(commands.map(command => ({
	// ...
	task: async (ctx, task) => {
		if(isCI) {
			return $({stdio: "inherit"})`${command}`;
		}
		// ...
	},
})), {
	// ...
	rendererSilent: isCI,
});

await tasks.run({ /* ... */ });
```
