### ISSUE TITLE
Thank you ♥

### ISSUE THREAD

**Issue by IgnusG** [cenk1cenk2/listr2#8]
This is a a big **thank you** for your efforts in developing this!  

I was struggling to integrate `listr` in my company's publishing pipeline since it required custom inputs and then I came across `listr2`. Simply Awesome! Worked perfectly and the types are a huge bonus too. Not to mention the fast responses with fixing stray issues and bugs, I encountered along the way.  

Just wanted to extend my thanks for this effort.

I hope more projects can benefit from your effort and this package in the future ❤️ 
*Feel free to close this issue once you read it* 🙂

(*if possible, leave it unlocked for other people to leave their own thank you's in the future 😉*)

**Comment by cenk1cenk2** [comment]
Thanks for all the kind words. 

Since it does not have automated tests because I was lazy at the time, it was not easy to foresee the issues. Happy to make things a bit easier at work, it is always a thing that can make anyone happy.
